# Generated by Django 4.1.5 on 2023-02-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_warehouse_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FOO', 'Food'), ('BEA', 'Beauty'), ('CLO', 'Clothes'), ('HEA', 'Health'), ('ACC', 'Accessories'), ('SHO', 'Shoes')], max_length=3),
        ),
    ]
